#
Summary:	List of blacklisted OpenSSH RSA and DSA keys
Name:		openssh-blacklist
Version:	0.2.1
Release:	2
License:	GPLv3
Group:		Applications
Source0:	http://ftp.debian.org/debian/pool/main/o/openssh-blacklist/%{name}_%{version}.tar.gz
# Source0-md5:	726869883bff9953537b2a07bbfef3c8
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Contains a set of default SSH keys that were known to have been
generated by Debian machines during the time when the Debian OpenSSL
package had a broken Random Number Generator.

%prep
%setup -q

%build
mkdir tmp

for i in `ls [RD]SA-* | cut -d. -f1 | sort -u`; do
	cat debian/blacklist.prefix > tmp/blacklist.$i
	cat $i.* | cut -b13- | sort >> tmp/blacklist.$i
done

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT%{_sysconfdir}/ssh
install tmp/blacklist.* $RPM_BUILD_ROOT%{_sysconfdir}/ssh

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc README debian/README.Debian debian/copyright
%{_sysconfdir}/ssh/blacklist.*
